version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.BE
    container_name: backend
    ports:
      - 8080:8080
    # env_file:
    #   - ./backend/.env
    # volumes:
    #   - ./:/app
  frontend:
    build:
      context: .
      dockerfile: dockerfile.FE
    container_name: frontend
    ports:
      - 3000:3000
    # env_file:
    #   - ./frontend/.env
    # volumes:
    #   - ./:/app
